environment:
  matrix:
  - PYTHON: "C:\\Python35"
  - PYTHON: "C:\\Python35-x64"
  - PYTHON: "C:\\Python36"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python37"
  - PYTHON: "C:\\Python37-x64"

matrix:
  fast_finish: true

build: false

cache:
- '%LOCALAPPDATA%\pip\Cache'

install:
- ps: |
    $Env:PATH = "$Env:PYTHON;$Env:PYTHON\Scripts;$Env:PATH"
    $Env:PYTHONUNBUFFERED = 1
    python -mpip install --upgrade pip setuptools wheel
    python -mpip install --upgrade pytest pytest-cov codecov
    python setup.py bdist_wheel
    python -mpip install $(Get-Item dist\*.whl)
    $host.SetShouldExit($LastExitCode)  # The only thing that matters, regardless of stderr.

test_script:
- ps: |
    python -mpytest --doctest-modules --cov --pyargs hmmlearn

artifacts:
- path: dist\*
