dist: xenial
sudo: true

language: python
python:
- "2.7"
- "3.4"
- "3.7"

install: |
  set -e
  python -mpip install --upgrade pip setuptools wheel
  python -mpip install --upgrade pytest pytest-cov codecov
  python -mpip install .
  python -mpip list
script: |
  python -mpytest --doctest-modules --cov --pyargs hmmlearn
after_success: |
  codecov
